-- MySQL Script generated by MySQL Workbench
-- Mon Mar  5 00:45:04 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ng-courses
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ng-courses` ;

-- -----------------------------------------------------
-- Schema ng-courses
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ng-courses` DEFAULT CHARACTER SET utf8 ;
USE `ng-courses` ;

-- -----------------------------------------------------
-- Table `ng-courses`.`teacher`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ng-courses`.`teacher` ;

CREATE TABLE IF NOT EXISTS `ng-courses`.`teacher` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `middleName` VARCHAR(45) NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ng-courses`.`course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ng-courses`.`course` ;

CREATE TABLE IF NOT EXISTS `ng-courses`.`course` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `startDate` DATE NOT NULL,
  `endDate` DATE NOT NULL,
  `teacherId` INT NOT NULL,
  PRIMARY KEY (`id`, `teacherId`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_course_teacher_idx` (`teacherId` ASC),
  CONSTRAINT `fk_course_teacher`
    FOREIGN KEY (`teacherId`)
    REFERENCES `ng-courses`.`teacher` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ng-courses`.`student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ng-courses`.`student` ;

CREATE TABLE IF NOT EXISTS `ng-courses`.`student` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `middleName` VARCHAR(45) NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ng-courses`.`student_has_course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ng-courses`.`student_has_course` ;

CREATE TABLE IF NOT EXISTS `ng-courses`.`student_has_course` (
  `studentId` INT NOT NULL,
  `courseId` INT NOT NULL,
  `courseTeacherId` INT NOT NULL,
  PRIMARY KEY (`studentId`, `courseId`, `courseTeacherId`),
  INDEX `fk_student_has_course_course1_idx` (`courseId` ASC, `courseTeacherId` ASC),
  INDEX `fk_student_has_course_student1_idx` (`studentId` ASC),
  CONSTRAINT `fk_student_has_course_student1`
    FOREIGN KEY (`studentId`)
    REFERENCES `ng-courses`.`student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_has_course_course1`
    FOREIGN KEY (`courseId` , `courseTeacherId`)
    REFERENCES `ng-courses`.`course` (`id` , `teacherId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
